import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  tempColorPrimary: null,
  tempColorPrimaryBg: null,
  tempColorPrimaryBgHover: null,
  tempColorPrimaryBorder: null,
  tempColorPrimaryBorderHover: null,
  tempColorPrimaryHover: null,
  tempColorPrimaryActive: null,
  tempColorPrimaryTextHover: null,
  tempColorPrimaryText: null,
  tempColorPrimaryTextActive: null,
  tempColorSuccess: null,
  tempColorSuccessBg: null,
  tempColorSuccessBgHover: null,
  tempColorSuccessBorder: null,
  tempColorSuccessBorderHover: null,
  tempColorSuccessHover: null,
  tempColorSuccessActive: null,
  tempColorSuccessTextHover: null,
  tempColorSuccessText: null,
  tempColorSuccessTextActive: null,
  tempColorWarning: null,
  tempColorWarningBg: null,
  tempColorWarningBgHover: null,
  tempColorWarningBorder: null,
  tempColorWarningBorderHover: null,
  tempColorWarningHover: null,
  tempColorWarningActive: null,
  tempColorWarningTextHover: null,
  tempColorWarningText: null,
  tempColorWarningTextActive: null,
  tempColorError: null,
  tempColorErrorBg: null,
  tempColorErrorBgHover: null,
  tempColorErrorBorder: null,
  tempColorErrorBorderHover: null,
  tempColorErrorHover: null,
  tempColorErrorActive: null,
  tempColorErrorTextHover: null,
  tempColorErrorText: null,
  tempColorErrorTextActive: null,
  tempColorInfo: null,
  tempColorLink: null,
  tempColorLinkHover: null,
  tempColorLinkActive: null,
  tempColorTextBase: null,
  tempColorBgBase: null,
  tempColorText: null,
  tempColorTextSecondary: null,
  tempColorTextTertiary: null,
  tempColorTextQuaternary: null,
  tempColorBorder: null,
  tempColorBorderSecondary: null,
  tempColorFill: null,
  tempColorFillSecondary: null,
  tempColorFillTertiary: null,
  tempColorFillQuaternary: null,
  tempColorBgContainer: null,
  tempColorBgElevated: null,
  tempColorBgLayout: null,
  tempColorBgSpotlight: null,
  tempColorBgMask: null,
  tempFontSize: null,
  tempFontSizeSM: null,
  tempFontSizeLG: null,
  tempFontSizeXL: null,
  tempFontSizeHeading1: null,
  tempFontSizeHeading2: null,
  tempFontSizeHeading3: null,
  tempFontSizeHeading4: null,
  tempFontSizeHeading5: null,
  tempLineHeight: null,
  tempLineHeightSM: null,
  tempLineHeightLG: null,
  tempLineHeightHeading1: null,
  tempLineHeightHeading2: null,
  tempLineHeightHeading3: null,
  tempLineHeightHeading4: null,
  tempLineHeightHeading5: null,
  tempSizeStep: null,
  tempSizeUnit: null,
  tempMarginXXS: null,
  tempMarginXS: null,
  tempMarginSM: null,
  tempMargin: null,
  tempMarginMD: null,
  tempMarginLG: null,
  tempMarginXL: null,
  tempMarginXXL: null,
  tempPaddingXXS: null,
  tempPaddingXS: null,
  tempPaddingSM: null,
  tempPadding: null,
  tempPaddingMD: null,
  tempPaddingLG: null,
  tempPaddingXL: null,
  tempBorderRadius: null,
  tempBorderRadiusXS: null,
  tempBorderRadiusSM: null,
  tempBorderRadiusLG: null,
  tempBoxShadow: null,
  tempBoxShadowSecondary: null,
  tempWireframe: null,
  tempFontFamily: null,
};

const tempThemeSlice = createSlice({
    name: "tempTheme",
    initialState,
    reducers: {
        resetTemp(state) {
            return initialState;
        },
        resetTempByKey(state, action) {
            const { key } = action.payload;
            state[key] = initialState[key];
        },
        setTempByKey(state, action) {
            const { key, value } = action.payload;
            state[key] = value;
        }
    },
})

export const { resetTemp, resetTempByKey, setTempByKey } = tempThemeSlice.actions;
export const tempThemeReducer = tempThemeSlice.reducer;