// src/components/ThemeProviderWrapper.jsx
import { ConfigProvider, theme as antdTheme } from "antd";
import { useEffect, useState } from "react";
import { useSelector } from "react-redux";
import { loadGoogleFont } from "../../utils/loadGoogleFont";

const ThemeProviderWrapper = ({ children }) => {


  const [fadeClass, setFadeClass] = useState("fade-theme show");

  const { 
    themeMode,
    colorPrimary,
    colorPrimaryBg,
    colorPrimaryBgHover,
    colorPrimaryBorder,
    colorPrimaryBorderHover,
    colorPrimaryHover,
    colorPrimaryActive,
    colorPrimaryTextHover,
    colorPrimaryText,
    colorPrimaryTextActive,
    colorSuccess,
    colorSuccessBg,
    colorSuccessBgHover,
    colorSuccessBorder,
    colorSuccessBorderHover,
    colorSuccessHover,
    colorSuccessActive,
    colorSuccessTextHover,
    colorSuccessText,
    colorSuccessTextActive,
    colorWarning,
    colorWarningBg,
    colorWarningBgHover,
    colorWarningBorder,
    colorWarningBorderHover,
    colorWarningHover,
    colorWarningActive,
    colorWarningTextHover,
    colorWarningText,
    colorWarningTextActive,
    colorError,
    colorErrorBg,
    colorErrorBgHover,
    colorErrorBorder,
    colorErrorBorderHover,
    colorErrorHover,
    colorErrorActive,
    colorErrorTextHover,
    colorErrorText,
    colorErrorTextActive,
    colorLink,
    colorLinkHover,
    colorLinkActive,
    colorTextBase,
    colorBgBase,
    colorText,
    colorTextSecondary,
    colorTextTertiary,
    colorTextQuaternary,
    colorBorder,
    colorBorderSecondary,
    colorFill,
    colorFillSecondary,
    colorFillTertiary,
    colorFillQuaternary,
    colorBgContainer,
    colorBgElevated,
    colorBgLayout,
    colorBgSpotlight,
    colorBgMask,
    sizeMode,
    fontSizeSM,
    fontSizeLG,
    fontSizeXL,
    fontSizeHeading1,
    fontSizeHeading2,
    fontSizeHeading3,
    fontSizeHeading4,
    fontSizeHeading5,
    lineHeight,
    lineHeightSM,
    lineHeightLG,
    lineHeightHeading1,
    lineHeightHeading2,
    lineHeightHeading3,
    lineHeightHeading4,
    lineHeightHeading5,
    sizeStep,
    sizeUnit,
    marginXXS,
    marginXS,
    marginSM,
    margin,
    marginMD,
    marginLG,
    marginXL,
    marginXXL,
    paddingXXS,
    paddingXS,
    paddingSM,
    padding,
    paddingMD,
    paddingLG,
    paddingXL,
    borderRadius,
    borderRadiusXS,
    borderRadiusSM,
    borderRadiusLG,
    boxShadow,
    boxShadowSecondary,
    wireframe,
    fontSize,
    fontFamily
   } = useSelector(
    (state) => state.theme
  );


  const tokenRaw = {
    colorPrimary,
    colorPrimaryBg,
    colorPrimaryBgHover,
    colorPrimaryBorder,
    colorPrimaryBorderHover,
    colorPrimaryHover,
    colorPrimaryActive,
    colorPrimaryTextHover,
    colorPrimaryText,
    colorPrimaryTextActive,
    colorSuccess,
    colorSuccessBg,
    colorSuccessBgHover,
    colorSuccessBorder,
    colorSuccessBorderHover,
    colorSuccessHover,
    colorSuccessActive,
    colorSuccessTextHover,
    colorSuccessText,
    colorSuccessTextActive,
    colorWarning,
    colorWarningBg,
    colorWarningBgHover,
    colorWarningBorder,
    colorWarningBorderHover,
    colorWarningHover,
    colorWarningActive,
    colorWarningTextHover,
    colorWarningText,
    colorWarningTextActive,
    colorError,
    colorErrorBg,
    colorErrorBgHover,
    colorErrorBorder,
    colorErrorBorderHover,
    colorErrorHover,
    colorErrorActive,
    colorErrorTextHover,
    colorErrorText,
    colorErrorTextActive,
    colorLink,
    colorLinkHover,
    colorLinkActive,
    colorTextBase,
    colorBgBase,
    colorText,
    colorTextSecondary,
    colorTextTertiary,
    colorTextQuaternary,
    colorBorder,
    colorBorderSecondary,
    colorFill,
    colorFillSecondary,
    colorFillTertiary,
    colorFillQuaternary,
    colorBgContainer,
    colorBgElevated,
    colorBgLayout,
    colorBgSpotlight,
    colorBgMask,
    sizeMode,
    fontSizeSM,
    fontSizeLG,
    fontSizeXL,
    fontSizeHeading1,
    fontSizeHeading2,
    fontSizeHeading3,
    fontSizeHeading4,
    fontSizeHeading5,
    lineHeight,
    lineHeightSM,
    lineHeightLG,
    lineHeightHeading1,
    lineHeightHeading2,
    lineHeightHeading3,
    lineHeightHeading4,
    lineHeightHeading5,
    sizeStep,
    sizeUnit,
    marginXXS,
    marginXS,
    marginSM,
    margin,
    marginMD,
    marginLG,
    marginXL,
    marginXXL,
    paddingXXS,
    paddingXS,
    paddingSM,
    padding,
    paddingMD,
    paddingLG,
    paddingXL,
    borderRadius,
    borderRadiusXS,
    borderRadiusSM,
    borderRadiusLG,
    boxShadow,
    boxShadowSecondary,
    fontSize,
    fontFamily
  }

  const filteredToken = Object.fromEntries(
    Object.entries(tokenRaw).filter(([_,v]) => v !== undefined && v !== null) 
  )

  useEffect(() => {
    if(fontFamily) {
      loadGoogleFont(fontFamily);
    }
  }, [fontFamily])

  const config = {
    token: filteredToken,
    algorithm: [
      themeMode === "dark" ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
      sizeMode === true? antdTheme.defaultAlgorithm : antdTheme.compactAlgorithm,
    ]
  };

  useEffect(() => {
    setFadeClass("fade-theme");
    const timeout = setTimeout(() => setFadeClass("fade-theme show"), 10);
    return () => clearTimeout(timeout);
  }, [themeMode]);

  return <ConfigProvider theme={config}>{children}</ConfigProvider>;
};

export default ThemeProviderWrapper;
