server:
  port: 8080
spring:
  application:
    name: RICE_SALE_SYSTEM
  datasource:
    url: jdbc:postgresql://localhost:5432/rice_sale_system
    username: postgres
    password: 1409
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
api:
  google-font:
    key: AIzaSyBFrVd78WDzOu4181HeyxnaFUMoMgoMPbI


app:
  security:
    algorithm: HS512
    secret: 1409
    jwt:
      access-token:
        secret: mySecretKey123
        expiration: 15m
      refresh-token:
        secret: mySecretKey456
        expiration: 30d
